# Generated by Django 5.1.3 on 2024-11-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_customuser_is_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
