# Generated by Django 5.1.3 on 2025-01-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorialPayment', '0002_remove_payment_stripe_payment_intend_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorwallet',
            name='description',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
