# Generated by Django 5.1.3 on 2025-01-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorialPayment', '0003_tutorwallet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorwallet',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
