# Generated by Django 5.1.3 on 2025-01-01 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TutorialPayment', '0004_alter_tutorwallet_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorwallet',
            name='description',
        ),
    ]
