# Generated by Django 5.1.4 on 2025-01-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedcourse',
            name='tutor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
