# Generated by Django 5.1.4 on 2025-01-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_purchasedcourse_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedcourse',
            name='tutor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
