# Generated by Django 5.1.4 on 2025-01-24 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_payment_options_payment_last_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedcourse',
            name='user',
        ),
        migrations.CreateModel(
            name='PurchasedCourseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('purchased_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_users', to='payment.purchasedcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_course_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('purchased_course', 'user')},
            },
        ),
    ]
