# Generated by Django 5.1.4 on 2025-01-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselesson',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
