# Generated by Django 5.1.3 on 2024-12-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_tutorial_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='tutorial',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
