# Generated by Django 5.1.3 on 2024-12-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorials', '0002_remove_video_video_url_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
