# Generated by Django 5.1.3 on 2024-12-29 12:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorials', '0005_remove_video_video_file_video_cloudinary_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cloudinary_url',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='video'),
            preserve_default=False,
        ),
    ]
