# Generated by Django 5.1.3 on 2025-01-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorials', '0006_alter_video_cloudinary_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/'),
        ),
    ]
