# Generated by Django 5.1.4 on 2025-03-14 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_alter_courselesson_order'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_6e3964_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient'], name='notificatio_recipie_be3f1a_idx'),
        ),
    ]
